"""Dependency-free constants shared by CEC runtime and evaluators.

This module is intentionally limited to scalar protocol constants.  Habitat
evaluation processes may import it without loading OpenCV, feature matchers,
or any GPU runtime.  The geometry implementation imports these constants; it
is not itself the source of the protocol boundary.
"""

CERTIFIED_RELOCALIZATION_SCHEMA_VERSION = 3
CERTIFIED_GEOMETRY_CERTIFICATE_VERSION = 2
CERTIFIED_CANDIDATE_TOP_K = 8
CERTIFIED_CANDIDATE_MIN_GAP = 4
CERTIFIED_MINIMUM_ANCHOR = 8
CERTIFIED_EPIPOLAR_THRESHOLD_PX = 1.5
CERTIFICATE_MIN_INLIERS = 16
CERTIFICATE_MIN_QUERY_COVERAGE = 0.05
CERTIFICATE_MIN_REFERENCE_COVERAGE = 0.05
CERTIFICATE_MAX_REPROJECTION_RMSE_PX = 2.0
STRICT_AUTHORITY_POLICY = "strict_certificate"
UNTHRESHOLDED_WITNESS_AUTHORITY_POLICY = "pnp_pose_available"
SUPPORTED_AUTHORITY_POLICIES = (
    STRICT_AUTHORITY_POLICY,
    UNTHRESHOLDED_WITNESS_AUTHORITY_POLICY,
)


__all__ = [
    "CERTIFICATE_MAX_REPROJECTION_RMSE_PX",
    "CERTIFICATE_MIN_INLIERS",
    "CERTIFICATE_MIN_QUERY_COVERAGE",
    "CERTIFICATE_MIN_REFERENCE_COVERAGE",
    "CERTIFIED_CANDIDATE_MIN_GAP",
    "CERTIFIED_CANDIDATE_TOP_K",
    "CERTIFIED_EPIPOLAR_THRESHOLD_PX",
    "CERTIFIED_GEOMETRY_CERTIFICATE_VERSION",
    "CERTIFIED_MINIMUM_ANCHOR",
    "CERTIFIED_RELOCALIZATION_SCHEMA_VERSION",
    "STRICT_AUTHORITY_POLICY",
    "SUPPORTED_AUTHORITY_POLICIES",
    "UNTHRESHOLDED_WITNESS_AUTHORITY_POLICY",
]
