"""Frozen constants for the 2026-09-03 route-tangent mechanism audit."""

SEALED_DENSE_HISTORY_INDICES = (16, 39, 40)
ROUTE_TANGENT_CONFIRMATION_HISTORY_INDEX = 39

MAX_ABSOLUTE_PATH_LENGTH_BIAS_FRACTION = 0.15
MAX_HISTORY_ENDPOINT_ERROR_M = 1.25
MIN_TRANSLATED_BEARING_WITHIN_30_FRACTION = 0.80
MAX_TRANSLATED_BEARING_MEDIAN_DEG = 20.0
CONTROLLER_RADIUS_M = 2.5
